[versions]
# often changed version numbers
adventure = "4.17.0"
adventure-platform = "4.3.4"
commandapi = "10.1.2"

actions = "1.0.0-SNAPSHOT"

[libraries]

#
# Plugin Dependencies
#
    # ProtocolLib https://github.com/dmulloy2/ProtocolLib
    # Repo: Maven Central
    protocol-lib = { module = "net.dmulloy2:ProtocolLib", version = "5.4.0" }
    # PacketEvents https://docs.packetevents.com/getting-started
    # Repo: https://repo.codemc.io/repository/maven-releases/
    packet-events = { module = "com.github.retrooper:packetevents-spigot", version = "2.9.5" }


    # PlaceholderAPI https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Hook-into-PlaceholderAPI
    # Repo: https://repo.extendedclip.com/content/repositories/placeholderapi
    placeholderapi = { module = "me.clip:placeholderapi", version = "2.11.6" }

    # MythicMobs https://git.lumine.io/mythiccraft/MythicMobs/-/wikis/API
    # Repo: https://mvn.lumine.io/repository/maven-public/
    mythicmobs = { module = "io.lumine:Mythic-Dist", version = "5.7.0-SNAPSHOT" }
    # https://git.lumine.io/mythiccraft/mythiccrucible
    # Repo: https://mvn.lumine.io/repository/maven-public/
    mythic-crucible = { module = "io.lumine:MythicCrucible-API", version = "2.2.0-SNAPSHOT" }

    # MMOItems https://gitlab.com/phoenix-dvpmt/mmoitems
    # Repo: https://nexus.phoenixdevt.fr/repository/maven-public/
    mmoitems = { module = "net.Indyuce:MMOItems-API", version = "6.9.5-SNAPSHOT" }
    mythic-lib-dist = { module = "io.lumine:MythicLib-dist", version = "1.7.1-SNAPSHOT" }

    # WorldEdit https://worldedit.enginehub.org/en/latest/api/
    # Repo: https://maven.enginehub.org/repo/
    worldedit-bukkit = { module = "com.sk89q.worldedit:worldedit-bukkit", version = "7.4.0-SNAPSHOT" }

    # ModelEngine https://git.lumine.io/mythiccraft/model-engine-4/-/wikis/API
    # Repo: https://mvn.lumine.io/repository/maven-public/
    modelengine = { module = "com.ticxo.modelengine:ModelEngine", version = "R4.0.9" }
    modelengine-api = { module = "com.ticxo.modelengine:api", version = "R3.1.8" } # not needed just an older version of ModelEngine

    # EcoItems https://plugins.auxilor.io/ecoitems/api
    # Repo: https://repo.auxilor.io/repository/maven-public/
    ecoitems = { module = "com.willfp:EcoItems", version = "5.64.0" }
    eco = { module = "com.willfp:eco", version = "6.73.0" }
    libreforge = { module = "com.willfp:libreforge", version = "4.36.0" }

    # BlockLocker https://github.com/rutgerkok/BlockLocker
    # Repo: https://repo.codemc.org/repository/maven-public/
    blocklocker = { module = "nl.rutgerkok:blocklocker", version = "1.13-SNAPSHOT" }

    #
    # Libraries that are included in MC
    # But are not exposed
    #
    commons-io = { module = "commons-io:commons-io", version = "2.11.0" }

#
# Libraries that are in Maven Central
# And therefore can be in the plugins.yml > libraries section
#
    gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
    commons-lang3 = { module = "org.apache.commons:commons-lang3", version = "3.14.0" }
    joml = { module = "org.joml:joml", version = "1.10.5" }  # Because pre 1.19.4 api does not have this in the server-jar
    annotations = { module = "org.jetbrains:annotations", version = "26.0.2" }

    # Adventure
    adventure-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
    adventure-plain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "adventure" }
    adventure-ansi = { module = "net.kyori:adventure-text-serializer-ansi", version.ref = "adventure" }
    adventure-platform = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-platform" }

    # Actions https://github.com/iGabyTM/actions
    actions-core = { module = "me.gabytm.util:actions-core", version.ref = "actions" }
    actions-spigot = { module = "me.gabytm.util:actions-spigot", version.ref = "actions" }

    # Spring Expressions
    spring-expression = { module = "org.springframework:spring-expression", version = "6.0.6" }

    # MCLogs https://github.com/aternosorg/mclogs
    mc-logs = { module = "gs.mclo:java", version = "2.2.1" }

    # http https://hc.apache.org/httpcomponents-client-5.5.x/
    # No clue where its used in the code tho??
    http = {module = "org.apache.httpcomponents:httpmime", version = "4.5.13"}

#
# Libraries that are shaded and relocated
#

    # BStats https://github.com/Bastian/bstats-metrics
    # Repo: Maven Central
    bstats = { module = "org.bstats:bstats-bukkit", version = "3.1.0" }

    # Creative API https://github.com/unnamed/creative
    # Repo: Maven Central
    creative = { module = "team.unnamed:creative-api", version = "1.7.3" }

    # CommandAPI https://commandapi-live-docs.jorel.dev/setup_dev.html
    # Repo: Maven Central
    commandapi = { module = "dev.jorel:commandapi-bukkit-shade", version.ref = "commandapi" }

    # JSON
    javax-json = { module = "org.glassfish:javax.json", version = "1.1.4" }

    # ProtectionLib
    # Repo: https://repo.oraxen.com/releases/
    protectionlib = { module = "io.th0rgal:protectionlib", version = "1.8.0" }

    # InventoryFramework https://github.com/stefvanschie/IF
    # Repo: Maven Central
    inventoryframework = { module = "com.github.stefvanschie.inventoryframework:IF", version = "0.11.3" }

    # Repo: Maven Central
    # https://github.com/mfnalex/CustomBlockData
    custom-block-data = { module = "com.jeff-media:custom-block-data", version = "2.2.5" }
    # https://github.com/mfnalex/MorePersistentDataTypes
    more-persistent-data-types = { module = "com.jeff-media:MorePersistentDataTypes", version = "2.4.0" }
    # https://github.com/mfnalex/PersistentDataSerializer
    persistent-data-serializer = { module = "com.jeff-media:persistent-data-serializer", version = "1.0" }

    # Triumph GUI https://github.com/TriumphTeam/triumph-gui
    # Repo: Maven Central
    triumph-gui = { module = "dev.triumphteam:triumph-gui", version = "3.1.10" }

[bundles]
# libraries that are included somewher but not exposed
libraries-included = [
    "commons-io", # included in minecraft
    "actions-core" # included in actions-spigot
]
libraries-bukkit = ["spring-expression", "http", "joml",
    "adventure-ansi", "adventure-minimessage", "adventure-plain", "adventure-platform",
    "gson", "commons-lang3", "mc-logs",
    "creative"
]
libraries-shade = [
    "bstats", "annotations",
    "triumph-gui", "commandapi",
    "javax-json", "protectionlib",
    "inventoryframework",
    "custom-block-data", "more-persistent-data-types", "persistent-data-serializer",
    "actions-spigot"
]
plugins = [
    "mythic-lib-dist", "mmoitems", # mmo items
    "mythic-crucible",  # mythic curcible
    "mythicmobs", # MythicMobs
    "modelengine", # Model Engine
    "packet-events", # PacketEvents
    "protocol-lib", # ProtocolLib
    "placeholderapi", # PlaceholderAPI
    "worldedit-bukkit", # WorldEdit
    "eco", "libreforge", "ecoitems", # EcoÍtems
    "blocklocker", # BlockLocker
]